### ISSUE TITLE
TODO: Add Unit Tests from Bobo 2.0.7 (Java)

### ISSUE THREAD

**Issue by NightOwl888** [zhengchun/Bobo-Browse.Net#13]
As mentioned in #6, we need to add the unit tests from [v2.5.1](https://github.com/senseidb/bobo/tree/461cf762ebc4bfcbea4b807073bc86020446a208/test/src/com/browseengine/bobo) in order to ensure we have parity with that version. We already have parity with the codeplex version, which is great.

This is essentially the same issue as [discussion 361478](https://bobo.codeplex.com/discussions/361478) on codeplex.

@zhengchun 

Do you have any time available to migrate these tests? I am currently too busy for the next few days, but should be able to start working on it sometime this week.

I plan to wait a couple of days for any feedback on the versioning, then to move this project onto NuGet as an alpha. I will also put together a release document at that point. Once we have finished migrating the unit tests to c# and have them all passing, we can go to beta. Official release can happen after any bugs that are reported in alpha and beta have been fixed and, if there are a lot of them, a stabilization period has passed.

**Comment by NightOwl888** [comment]
@zhengchun 

Closing this issue because the work in the title has already been done.

As for using `NumericUtils.PrefixCodedToXXX`, this is not the right approach. BoboBrowse does not support NumericField. I confirmed this by porting @dtosato's integer test to Java:

```
F:\Projects\bobo-test>java -jar target\bobo-test-0.1.0.jar
Hello world!
Exception in thread "main" java.lang.NumberFormatException: For input string: "`
   ☺"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.
java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.browseengine.bobo.facets.data.TermIntList.parse(TermIntList.java:
25)
        at com.browseengine.bobo.facets.data.TermIntList.add(TermIntList.java:48
)
        at com.browseengine.bobo.facets.data.FacetDataCache.load(FacetDataCache.
java:141)
        at com.browseengine.bobo.facets.impl.RangeFacetHandler.load(RangeFacetHa
ndler.java:148)
        at com.browseengine.bobo.facets.impl.RangeFacetHandler.load(RangeFacetHa
ndler.java:31)
        at com.browseengine.bobo.facets.FacetHandler.load(FacetHandler.java:145)

        at com.browseengine.bobo.facets.FacetHandler.loadFacetData(FacetHandler.
java:150)
        at com.browseengine.bobo.api.BoboIndexReader.loadFacetHandler(BoboIndexR
eader.java:412)
        at com.browseengine.bobo.api.BoboIndexReader.loadFacetHandlers(BoboIndex
Reader.java:430)
        at com.browseengine.bobo.api.BoboIndexReader.facetInit(BoboIndexReader.j
ava:613)
        at com.browseengine.bobo.api.BoboIndexReader.facetInit(BoboIndexReader.j
ava:619)
        at com.browseengine.bobo.api.BoboIndexReader.facetInit(BoboIndexReader.j
ava:605)
        at com.browseengine.bobo.api.BoboIndexReader.getInstance(BoboIndexReader
.java:148)
        at com.browseengine.bobo.api.BoboIndexReader.getInstance(BoboIndexReader
.java:139)
        at bobo_test.HelloWorld.runBrowse(HelloWorld.java:134)
        at bobo_test.HelloWorld.main(HelloWorld.java:49)
```

Changing to use a Lucene Field with string formatting returns the correct results:

```
F:\Projects\bobo-test>java -jar target\bobo-test-0.1.0.jar
Hello world!
log4j:WARN No appenders could be found for logger (com.browseengine.bobo.api.Bob
oIndexReader).
log4j:WARN Please initialize the log4j system properly.
facets for number
- [* TO 3](3)
- [4 TO *](7)


F:\Projects\bobo-test>
```

So getting a format exception is the correct response in this case.
